# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mobile+
email: 
author: Nate Rickard
author_link: "https://github.com/naterickard"
description: > # this means to ignore newlines until "baseurl:"
  Ramblings on Xamarin, mobile, and cloud technologies.
disclaimer: I work at Microsoft, but opionions are my own.
copyright:   © Copyright 2016 Nate Rickard
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://naterickard.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: NateRickard/naterickard.github.io
twitter_username: TheNateRickard
github_username:  NateRickard
show_downloads: false
google_analytics: UA-92199836-1

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
